# Generated by Django 4.2.3 on 2023-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patients_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='contact_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
