# Generated by Django 4.2.3 on 2023-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patients_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
